specfile_path: CI/fapolicyd.spec

upstream_package_name: fapolicyd
downstream_package_name: fapolicyd
upstream_tag_template: v{version}

actions:
    post-upstream-clone:
      - bash -c "curl -L -o $(grep Source1 CI/fapolicyd.spec | cut -d ' ' -f 2 | sed -r \"s/%\{name\}/$(grep 'Name:' CI/fapolicyd.spec | cut -f 2 -d ' ')/g;s/%\{semodule_version\}/$(grep '%define semodule_version' CI/fapolicyd.spec | cut -f 3 -d ' ')/g\" | sed -r 's|(.*)#/(.*)|\2 \1|')"
      - bash -c "curl -L -o $(grep Source2 CI/fapolicyd.spec | cut -d ' ' -f 2 | sed -r 's|(.*)#/(.*)|\2 \1|')"

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-rawhide
      - epel-9
      - epel-8
