.TH "FAPOLICYD-CLI" "1" "July 2019" "Red Hat" "System Administration Utilities"
.SH NAME
fapolicyd-cli \- Fapolicyd CLI Tool
.SH SYNOPSIS
\fBfapolicyd-cli\fP [\fIoptions\fP]
.SH DESCRIPTION
Fapolicyd CLI Tool.
.SH OPTIONS
.TP
.B \-h, \-\-help
Prints this help message.
.TP
.B \-u, \-\-update
Notifies fapolicyd to perform update of database.
.SH "SEE ALSO"
.BR fapolicyd (8),
.BR fapolicyd.rules (5)
and
.BR fapolicyd.conf (5)

.SH AUTHOR
Zoltan Fridrich
