.TH "FAPOLICYD-CLI" "1" "February 2020" "Red Hat" "System Administration Utilities"
.SH NAME
fapolicyd-cli \- Fapolicyd CLI Tool
.SH SYNOPSIS
\fBfapolicyd-cli\fP [\fIoptions\fP]
.SH DESCRIPTION
The fapolicyd command line utility is a tool to tell the daemon that it needs to update the trust database. Normally, the daemon learns that the trust database needs updating because it uses a dnf plugin to inform it. However, you may install an rpm by hand and it can't see that a system package was installed or updated. Or perhaps the admin updates the fapolicyd.trust file and would like the changes to take effect immediately. In either of these cases, you would need to tell the daemon that it needs to do an update by running this command.
.SH OPTIONS
.TP
.B \-h, \-\-help
Prints this help message.
.TP
.B \-t, \-\-ftype /path/to/file
Prints the mime type of the file given. A full path must be specified. This command is intended to help get the ftype parameter of rules correct by seeing how fapolicyd will classify it. Fapolicyd may differ from the \fBfile\fP command.
.TP
.B \-l, \-\-list
Prints a listing of the fapolicyd rules file with a rule number to aid in troubleshooting or understanding of the debug messages.
.TP
.B \-u, \-\-update
Notifies fapolicyd to perform an update of the trust database.
.SH "SEE ALSO"
.BR fapolicyd (8),
.BR fapolicyd.rules (5),
.BR fapolicyd.trust (5),
and
.BR fapolicyd.conf (5)

.SH AUTHOR
Zoltan Fridrich
