.TH FAPOLICYD.FILTER: "26" "April 2023" "Red Hat" "System Administration Utilities"
.SH NAME
fapolicyd.filter \- fapolicyd filter configuration file
.SH DESCRIPTION
The file
.I /etc/fapolicyd/rpm-filter.filter.conf
was migrated to
.I /etc/fapolicyd/fapolicyd-filter.conf
or see
.BR fapolicyd.filter(5).



.SH "SEE ALSO"
.BR fapolicyd (8),
.BR fapolicyd-cli (1)
.BR fapolicy.rules (5)
and
.BR glob (7)

.SH AUTHOR
Radovan Sroka
