name: stable-fedora-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v2

    - name: getting envinronment info
      run: uname -a

    - name: print fedora version
      run: cat /etc/fedora-release

    - name: installing dependencies
      run: dnf -y install dnf-plugins-core python3-dnf-plugins-core util-linux; dnf -y builddep ./fapolicyd.spec

    - name: generate config files
      run: ./autogen.sh

    - name: configure
      run: ./configure --with-rpm --with-audit --disable-shared --disable-dependency-tracking

    - name: build
      run: make

    - name: check
      run: make check

    - name: dist
      run: make dist
