name: ubuntu22-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    steps:
    - uses: actions/checkout@v2

    - name: getting envinronment info
      run: uname -a

    - name: print version
      run: cat /etc/*release

    - name: Ensure up to date package list
      run: apt update

    - name: installing dependencies 1
      run: apt install -y autoconf automake libtool gawk gcc libdpkg-dev libmd-dev uthash-dev liblmdb-dev libudev-dev

    - name: installing dependencies 2
      run: apt install -y libgcrypt-dev libssl-dev libmagic-dev libcap-ng-dev  libseccomp-dev make debmake debhelper

    - name: generate config files
      run: ./autogen.sh

    - name: configure
      run: ./configure --without-rpm --with-audit --disable-shared --disable-dependency-tracking --with-deb

    - name: build
      run: make

    - name: check
      run: make check

    - name: dist
      run: make dist

    - name: build deb
      run: cd deb && ./build_deb.sh
